# Generated by Django 2.0.4 on 2018-04-18 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 17, 53, 28, 137163), verbose_name='Created Date'),
        ),
    ]
