# Generated by Django 2.0.4 on 2018-04-18 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20180418_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 19, 8, 6, 199930), verbose_name='Created Date'),
        ),
    ]
