# Generated by Django 2.0.4 on 2018-05-10 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20180418_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date'),
        ),
    ]
