# Generated by Django 2.0.4 on 2018-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20180510_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='location',
            field=models.CharField(max_length=30, verbose_name='location'),
        ),
    ]
