# Generated by Django 2.0.4 on 2018-05-10 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_auto_20180510_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Created Date'),
        ),
    ]
