# Generated by Django 2.0.4 on 2018-05-10 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_auto_20180510_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
