# Generated by Django 2.0.4 on 2018-05-10 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_auto_20180510_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
    ]
