# Generated by Django 2.0.4 on 2018-05-11 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_auto_20180511_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht22',
            name='date',
        ),
        migrations.AddField(
            model_name='dht22',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
        ),
    ]
