# Generated by Django 2.0.4 on 2018-05-11 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_auto_20180511_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht22',
            name='local_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 15, 28, 56, 452991, tzinfo=utc), verbose_name='Local Date'),
        ),
    ]
