# Generated by Django 2.0.4 on 2018-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_dht22_local_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='local_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Local Date'),
        ),
    ]
