# Generated by Django 2.0.4 on 2018-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_auto_20180511_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22',
            name='local_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Local Date'),
        ),
    ]
