# Generated by Django 2.0.4 on 2018-05-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0018_auto_20180511_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht22',
            name='local_datetime',
        ),
    ]
