# Generated by Django 2.0.4 on 2018-05-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0020_auto_20180511_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dht22',
            new_name='Dht22_bathroom',
        ),
    ]
