# Generated by Django 2.0.4 on 2018-05-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0021_auto_20180518_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dht22_bathroom',
            new_name='Dht22Bathroom',
        ),
    ]
