# Generated by Django 2.0.4 on 2018-05-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0022_auto_20180518_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22bathroom',
            name='datetime',
            field=models.DateTimeField(default='2018-05-18 23:13:14', verbose_name='Created Date'),
        ),
    ]
