# Generated by Django 2.0.4 on 2018-05-18 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0023_auto_20180518_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22bathroom',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date'),
        ),
    ]
