# Generated by Django 2.0.4 on 2018-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0026_auto_20180519_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht22bathroom',
            name='datetime',
            field=models.DateTimeField(verbose_name='Created Date'),
        ),
    ]
