# Generated by Django 2.0.4 on 2018-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0028_liveroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveroom',
            name='temp_value',
            field=models.CharField(max_length=30, verbose_name='DATA'),
        ),
    ]
