# Generated by Django 2.0.4 on 2018-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0030_auto_20180624_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroom',
            name='hum_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveroom',
            name='temp_value',
            field=models.FloatField(),
        ),
    ]
